"""
CleanSense AI — Report Generator

Produces a human-readable Markdown cleaning report.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List

import pandas as pd


def generate_cleaning_report(
    original_df: pd.DataFrame,
    cleaned_df: pd.DataFrame,
    operations: List[Dict[str, Any]],
    quality_score_before: int,
    quality_score_after: int,
) -> str:
    """
    Generate a Markdown cleaning report.

    Returns
    -------
    str  — Markdown text
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def _rows(df: pd.DataFrame) -> int:
        return len(df)

    def _missing(df: pd.DataFrame) -> int:
        return int(df.isna().sum().sum())

    def _dups(df: pd.DataFrame) -> int:
        return int(df.duplicated().sum())

    orig_rows = _rows(original_df)
    clean_rows = _rows(cleaned_df)
    orig_missing = _missing(original_df)
    clean_missing = _missing(cleaned_df)
    orig_dups = _dups(original_df)
    clean_dups = _dups(cleaned_df)

    applied = [o for o in operations if o.get("status") == "applied"]
    skipped = [o for o in operations if o.get("status") == "skipped"]
    errors = [o for o in operations if o.get("status") == "error"]

    lines: List[str] = []

    lines += [
        "# CleanSense AI — Cleaning Report",
        "",
        f"**Generated:** {now}",
        "",
        "---",
        "",
        "## Original Dataset Statistics",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Rows | {orig_rows:,} |",
        f"| Columns | {original_df.shape[1]} |",
        f"| Missing values | {orig_missing:,} |",
        f"| Duplicate rows | {orig_dups:,} |",
        f"| Data quality score | {quality_score_before}/100 |",
        "",
        "---",
        "",
        "## Cleaning Operations Applied",
        "",
    ]

    if applied:
        for op in applied:
            col = f"**{op['column']}**" if op.get("column") else "*(dataset-wide)*"
            lines.append(f"- ✅ `{op['action']}` on {col}: {op['message']}")
    else:
        lines.append("*No operations were applied.*")

    if skipped:
        lines += ["", "### Skipped / User-Rejected", ""]
        for op in skipped:
            col = f"**{op['column']}**" if op.get("column") else "*(dataset-wide)*"
            lines.append(f"- ⏭️ `{op['action']}` on {col}: {op['message']}")

    if errors:
        lines += ["", "### Errors", ""]
        for op in errors:
            col = f"**{op['column']}**" if op.get("column") else "*(dataset-wide)*"
            lines.append(f"- ❌ `{op['action']}` on {col}: {op['message']}")

    lines += [
        "",
        "---",
        "",
        "## Before vs After Comparison",
        "",
        "| Metric | Before | After | Change |",
        "|--------|--------|-------|--------|",
        f"| Rows | {orig_rows:,} | {clean_rows:,} | {clean_rows - orig_rows:+,} |",
        f"| Missing values | {orig_missing:,} | {clean_missing:,} | {clean_missing - orig_missing:+,} |",
        f"| Duplicate rows | {orig_dups:,} | {clean_dups:,} | {clean_dups - orig_dups:+,} |",
        f"| Quality score | {quality_score_before}/100 | {quality_score_after}/100 | {quality_score_after - quality_score_before:+} |",
        "",
        "---",
        "",
        "## Final Dataset Statistics",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Rows | {clean_rows:,} |",
        f"| Columns | {cleaned_df.shape[1]} |",
        f"| Missing values | {clean_missing:,} |",
        f"| Duplicate rows | {clean_dups:,} |",
        f"| Data quality score | {quality_score_after}/100 |",
        "",
        "---",
        "",
        "## Column Summary (After Cleaning)",
        "",
        "| Column | Type | Non-Null | Null % | Unique |",
        "|--------|------|----------|--------|--------|",
    ]

    for col in cleaned_df.columns:
        dtype = str(cleaned_df[col].dtype)
        non_null = int(cleaned_df[col].notna().sum())
        null_pct = round(cleaned_df[col].isna().mean() * 100, 1)
        unique = int(cleaned_df[col].nunique(dropna=True))
        lines.append(f"| {col} | {dtype} | {non_null:,} | {null_pct}% | {unique:,} |")

    lines += [
        "",
        "---",
        "",
        "*Report generated by CleanSense AI. Data processed securely — files are not permanently stored.*",
    ]

    return "\n".join(lines)
